language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.2
  - rbx-2
  - jruby-19mode
script: bundle exec rake test
env:
  - DEVISE_ORM=active_record
  - DEVISE_ORM=mongoid
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.r4.devise-3.2
  - Gemfile
install: "travis_retry bundle install"
services:
  - mongodb
matrix:
  exclude:
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.rails-3.2.x
      env: DEVISE_ORM=active_record
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.rails-3.2.x
      env: DEVISE_ORM=mongoid
